### PR TITLE
Fixed TinyFab LCD screen alignment when panel is reversed.

### PR DESCRIPTION
**Pull request by cls-nebadje**
Hi Maarten,

thank you for your work of tracking Smoothie's "edge". Today I finally had some seconds to spare to fix the problem with TinyFab's LCD which is offset by 4 pixels when it is operated in reversed/flipped mode.

To keep everything in one place (your repo for instance) I thought I just file a PR.

Happy new year, happy printing and best wishes from Switzerland!
cls

### CODE REVIEW

**Comment by cls-nebadje** [comment]
P.S.: I'm currently integrating the latest changes from edge, I managed to merge them all without any ambiguities.

Let's see if they break something. My printer is currently busy, but I'll report as soon as possible.

Did you notice, that the MCU on the TinyFab board has been marked as deprecated? This was already the case with your latest version.

**Comment by cls-nebadje** [comment]
Yep, seems to be good. I'm currently printing with the latest HEAD.

**Comment by cls-nebadje** [comment]
Here's the associated [release](https://github.com/cls-nebadje/TinyFab-Smoothieware/releases/tag/v1.0.1-edge-cb1a8aa)

**Comment by GewoonMaarten** [comment]
Thank you for your PR, I really appreciate it!

> Did you notice, that the MCU on the TinyFab board has been marked as deprecated? This was already the case with your latest version.

I did not. I guess we have to be careful with merging edge into our repo. They might start to remove code we need for the MCU. Thanks for the heads up!

**Comment by GewoonMaarten** [comment]
Looks good! Thanks for the readme update as well.

**Comment by elektronikworkshop** [comment]
Hi Maarten,

thanks for the merge, it was a pleasure! I already used this version a lot and no evident problems seemed to show up.

> I guess we have to be careful with merging edge into our repo. They might start to remove code we need for the MCU.

Yes, I thought so too. Fortunately, the current setup seems to be working pretty well, so I have no desire to upgrade just for the sake of upgrading. This changes though when bugs are found or cool features are added. So it's good to know.

**Comment by elektronikworkshop** [comment]
Something off topic in case you have the WiFi-version:

I'm not able to upload gcode with ESP3D to the SD-card without data corruption. I realized this when my print went erratic on me and I inspected the gcode which contained memory contents of the ESP firmware. Latter makes me guess that ESP3D has some severe buffer management issues by reading beyond the size of its RX buffers and actually performing a memory dump into the gcode file (block-interleaved with the actual data).

Smoothieware has the ```md5sum``` command which makes it possible to verify the upload and none succeeded up to now. What I haven't done yet is the verification of ```md5sum``` on its own.

This is a bit annoying since I found out that TinyFab just "stole" the binaries from another board/project and didn't release the source code (at least to my current knowledge). The firmware is a special version because it implements (a pretty crude) direct SPI access to the SD card by multiplexing the SPI bus. Which is of course a bit precarious as it can lead to data corruption in case both the ESP and the ARM access the SPI at the same time.

The official ESP3D repository didn't have this version (it popped up in some discussions though) but at least the alpha branch of 3.0 seems to provide direct SPI SD access but I was not too motivated up to now to debug this firmware as well. I'm tempted to do so, although it makes no sense if the upload can be remedied in some other way, or if I'm using it in the completely wrong fashion, or if someone else already worked on an updated firmware.

So my question is: do you have the WiFi version and if yes, what are your experiences with it?

In any case: it was a pleasure, take care and have a really good start with 2022!
cls

**Comment by GewoonMaarten** [comment]
Hi cls,

I'm sorry to say I can't help you as I don't have the WiFi version. I use the LCD and a 5 meter long USB cable as serial connection to upload gcode, which is really really slow :smile:

I looked at the schematic a bit, but at first glaze it may not be the multiplexers fault. The FST3257 has an input select for each port, so simultaneous writing/reading is probably not possible. Poor software implementation can mess all that up of course. But I'm just guessing, which is probably not helping you.

Sounds like a really annoying issue. If I can help let me know! Enjoy the new year!

**Pull request merged**
